final data = [
  {
    'country': 'Indonesia',
    'name': 'Bali',
    'rate': 4.8,
    'price': 150,
    'status': 'Featured',
    'image': 'assets/images/image_1.jpg',
  },
  {
    'country': 'Italy',
    'name': 'Rome',
    'rate': 4.9,
    'price': 180,
    'status': null,
    'image': 'assets/images/image_2.jpg',
  },
  {
    'country': 'USA',
    'name': 'New York',
    'rate': 4.7,
    'price': 220,
    'status': null,
    'image': 'assets/images/image_3.jpg',
  },
  {
    'country': 'Egypt',
    'name': 'Cairo',
    'rate': 4.5,
    'price': 90,
    'status': null,
    'image': 'assets/images/image_4.jpg',
  },
  {
    'country': 'Japan',
    'name': 'Tokyo',
    'rate': 4.9,
    'price': 200,
    'status': 'Popular',
    'image': 'assets/images/image_5.jpg',
  },
  {
    'country': 'Sydney',
    'name': 'Australia',
    'rate': 4.6,
    'price': 170,
    'status': null,
    'image': 'assets/images/image_6.jpg',
  },
  {
    'country': 'Uk',
    'name': 'London',
    'rate': 4.8,
    'price': 190,
    'status': null,
    'image': 'assets/images/image_7.jpg',
  },
  {
    'country': 'Barcelona',
    'name': 'Spain',
    'rate': 4.7,
    'price': 160,
    'status': null,
    'image': 'assets/images/image_8.jpg',
  },
];
